! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : simple_Initialize.f90
! Time                 : Tue May  6 12:17:10 2008
! Working directory    : /Users/lowe/work/manchester/chemistry/new-MAP/combined-MAP-code
! Equation file        : simple.kpp
! Output root filename : simple
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!
! This routine has been stripped down, to leave only the initialisation
!     of rate constants (and CFACTOR - but we might pass that in too?).
! All other initialisation should be performed in the python calling script now.
!



MODULE MAP_Python_Initialize

  USE MAP_Parameters, ONLY: dp
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialize - function to initialize concentrations
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Python_Initialize(START_P)


  USE MAP_Global

  logical, intent(in) :: START_P


! constant rate coefficients
  RCONST(3) = 2.2e-10
  RCONST(21) = 4e-12
  RCONST(25) = 2.6e-22
  RCONST(45) = 5e-14
  RCONST(47) = 5e-14
  RCONST(48) = 3e-12
  RCONST(51) = 1e-11
  RCONST(53) = 5.8e-16
  RCONST(55) = 1.4e-15
  RCONST(59) = 2e-12
  RCONST(60) = 1e-13
  RCONST(61) = 4e-13
  RCONST(62) = 4.7e-12
  RCONST(74) = 3.3e-10
  RCONST(77) = 9.5e-15
  RCONST(78) = 1.4e-14
  RCONST(80) = 1e-11
  RCONST(83) = 1.2e-11
  RCONST(84) = 6e-13
  RCONST(86) = 2.2e-12
  RCONST(87) = 3e-13
  RCONST(88) = 5e-11
  RCONST(90) = 8.7e-11
  RCONST(91) = 9e-11
  RCONST(92) = 1e-13
  RCONST(97) = 1.6e-10
  RCONST(100) = 1e-10
  RCONST(102) = 5.7e-11
  RCONST(131) = 5e-14
  RCONST(135) = 4.9e-11
  RCONST(138) = 4.1e-12
  RCONST(139) = 1.6e-12
  RCONST(140) = 1.5e-14
  RCONST(146) = 2.78e-13
  RCONST(155) = 4.5e-10
  RCONST(156) = 2.99e-11
  RCONST(161) = 2e-10
  RCONST(165) = 2.4
  RCONST(167) = 2.1e-10
  RCONST(168) = 1.5e-12
  RCONST(170) = 1.2e-12
  RCONST(184) = 1.5e-11
  RCONST(185) = 1.2e-10
  RCONST(186) = 2.09e-10
  RCONST(188) = 1.1e-15
  RCONST(189) = 3.3e-15
  RCONST(190) = 1.2e-10
  RCONST(191) = 1.2e-11
  RCONST(203) = 0
  RCONST(204) = 0
  RCONST(249) = 0.8
  RCONST(327) = 6e+09
  RCONST(354) = 3.3e+07
  RCONST(355) = 4.2e+06
  RCONST(368) = 2.4e+06
  RCONST(370) = 800000
  RCONST(385) = 3e+06
  RCONST(388) = 1830
  RCONST(486) = 1.8e+06
  RCONST(494) = 160000
  RCONST(498) = 110000
  RCONST(500) = 320
  RCONST(502) = 1e+13
  RCONST(504) = 91000
  RCONST(509) = 1.3e+09
  RCONST(511) = 280000
  RCONST(513) = 3.8e+09
  RCONST(523) = 1.3e+09
  RCONST(525) = 3.5e+08
  RCONST(527) = 280000
  RCONST(529) = 3.8e+09
  RCONST(705) = 0.8
  RCONST(783) = 6e+09
  RCONST(810) = 3.3e+07
  RCONST(811) = 4.2e+06
  RCONST(824) = 2.4e+06
  RCONST(826) = 800000
  RCONST(841) = 3e+06
  RCONST(844) = 1830
  RCONST(942) = 1.8e+06
  RCONST(950) = 160000
  RCONST(954) = 110000
  RCONST(956) = 320
  RCONST(958) = 1e+13
  RCONST(960) = 91000
  RCONST(965) = 1.3e+09
  RCONST(967) = 280000
  RCONST(969) = 3.8e+09
  RCONST(979) = 1.3e+09
  RCONST(981) = 3.5e+08
  RCONST(983) = 280000
  RCONST(985) = 3.8e+09
! END constant rate coefficients

	if(START_P) then
		! initialise model with H2O content and the (extra) H+ and OH- ions 
		! from the dissociation of H2O
		call h2o_init

		! record initial chemical concentrations
		cnp   = C
	end if


	!-------------------------------------
	contains	! subroutines and functions internal to the subroutine initialise
	!-------------------------------------


	subroutine h2o_init
	! Initialises the model with:
	! a) H2O content of aerosol particles
	! b) H+ and OH- content from dissociation of H2O

	use MAP_Parameters
	use MAP_Global
	use MAP_Rates
	use aerosol_microphysics
	
	real(kind=dp) :: Ctemp

	! ensure that vapour pressures and water content are up-to-date
	call aerosol_bin_sort(C(NVARST:NVAR),C(NFIXST:NSPEC),full=.true.)
	call update_rate_conversion()



	! initialise model with (extra) H+ and OH- ions equal to those 
	! expected from the dissociation of H2O
	    Ctemp = C(ind_BIN001001H2O)*conv_rate(1,1)*k_arr(1.0e-14,-6716e0,temp)
	    C(ind_BIN001001Hplu)  = C(ind_BIN001001Hplu)  + Ctemp**(0.5)
	    C(ind_BIN001001OHmin) = C(ind_BIN001001OHmin) + Ctemp**(0.5)
	    Ctemp = C(ind_BIN001002H2O)*conv_rate(1,2)*k_arr(1.0e-14,-6716e0,temp)
	    C(ind_BIN001002Hplu)  = C(ind_BIN001002Hplu)  + Ctemp**(0.5)
	    C(ind_BIN001002OHmin) = C(ind_BIN001002OHmin) + Ctemp**(0.5)


	end subroutine h2o_init

      
END SUBROUTINE Python_Initialize

! End of Initialize function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE MAP_Python_Initialize

